__attribute__((weak)) void Byond_GetVersion(void) {}
__attribute__((weak)) void Byond_GetDMBVersion(void) {}
__attribute__((weak)) void ByondValue_Clear(void) {}
__attribute__((weak)) void ByondValue_Type(void) {}
__attribute__((weak)) void ByondValue_IsNull(void) {}
__attribute__((weak)) void ByondValue_IsNum(void) {}
__attribute__((weak)) void ByondValue_IsStr(void) {}
__attribute__((weak)) void ByondValue_IsList(void) {}
__attribute__((weak)) void ByondValue_IsTrue(void) {}
__attribute__((weak)) void ByondValue_GetNum(void) {}
__attribute__((weak)) void ByondValue_GetRef(void) {}
__attribute__((weak)) void ByondValue_SetNum(void) {}
__attribute__((weak)) void ByondValue_SetStr(void) {}
__attribute__((weak)) void ByondValue_SetRef(void) {}
__attribute__((weak)) void ByondValue_Equals(void) {}
__attribute__((weak)) void Byond_ThreadSync(void) {}
__attribute__((weak)) void Byond_GetStrId(void) {}
__attribute__((weak)) void Byond_AddGetStrId(void) {}
__attribute__((weak)) void Byond_ReadVar(void) {}
__attribute__((weak)) void Byond_ReadVarByStrId(void) {}
__attribute__((weak)) void Byond_WriteVar(void) {}
__attribute__((weak)) void Byond_WriteVarByStrId(void) {}
__attribute__((weak)) void Byond_CreateList(void) {}
__attribute__((weak)) void Byond_ReadList(void) {}
__attribute__((weak)) void Byond_WriteList(void) {}
__attribute__((weak)) void Byond_ReadListAssoc(void) {}
__attribute__((weak)) void Byond_ReadListIndex(void) {}
__attribute__((weak)) void Byond_WriteListIndex(void) {}
__attribute__((weak)) void Byond_ReadPointer(void) {}
__attribute__((weak)) void Byond_WritePointer(void) {}
__attribute__((weak)) void Byond_CallProc(void) {}
__attribute__((weak)) void Byond_CallProcByStrId(void) {}
__attribute__((weak)) void Byond_CallGlobalProc(void) {}
__attribute__((weak)) void Byond_CallGlobalProcByStrId(void) {}
__attribute__((weak)) void Byond_ToString(void) {}
__attribute__((weak)) void Byond_Block(void) {}
__attribute__((weak)) void Byond_Length(void) {}
__attribute__((weak)) void Byond_LocateIn(void) {}
__attribute__((weak)) void Byond_LocateXYZ(void) {}
__attribute__((weak)) void Byond_New(void) {}
__attribute__((weak)) void Byond_NewArglist(void) {}
__attribute__((weak)) void Byond_Refcount(void) {}
__attribute__((weak)) void Byond_XYZ(void) {}
__attribute__((weak)) void ByondValue_IncRef(void) {}
__attribute__((weak)) void ByondValue_DecRef(void) {}
__attribute__((weak)) void Byond_TestRef(void) {}
